In [1]:
try:
    import numpy as np
except:
    print(1)

In [11]:
myarr = np.array([[3, 6, 32, 7]], np.int64)

In [12]:
myarr

array([[ 3,  6, 32,  7]], dtype=int64)

In [13]:
myarr.dtype

dtype('int64')

In [14]:
myarr.shape

(1, 4)

In [15]:
listarray = np.array([[1, 2, 3], [5, 8, 5], [0, 3, 1]])

In [16]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [17]:
listarray.dtype

dtype('int32')

In [18]:
listarray.shape

(3, 3)

In [19]:
listarray.size

9

In [20]:
np.array({34, 34})

array({34}, dtype=object)

In [27]:
zeros = np.zeros((2, 5))

In [22]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
zeros.dtype

dtype('float64')

In [24]:
zeros.shape

(2, 5)

In [25]:
zeros.size

10

In [28]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
rng = np.arange(15)

In [30]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
lspace = np.linspace(1, 5, 12)

In [32]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])